<a href="https://colab.research.google.com/github/sydobd/DL-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00_Pytorch_Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

###Creating Tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Get tensor back as Python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Pair of square brackets
vector.ndim

1

In [7]:
# 2x1 elements, since by default its a column matrix
vector.shape

torch.Size([2])

In [8]:
# MATRIX - write in capital letter is convention
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape
# we have 1 3x3 tensor

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR[0][1][1]

tensor(5)

In [17]:
TENSOR2 = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [18]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [19]:
TENSOR3 = torch.tensor([[[1,2,3,6],
                        [4,5,6,6],
                        [7,8,9,6]],
                       [[1,2,3,6],
                        [4,5,6,6],
                        [7,8,9,6]]])

In [20]:
TENSOR3.shape
# How many brackets after first bracket - 2
# How many brackets after second bracket - 3
# How many elements in last bracket - 4

torch.Size([2, 3, 4])

In [21]:
TENSOR3.ndim
# How many bracket pairs - 3

3

### Random Tensors

Why random tensors?

Random tensors are important because the way many neutral network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4612, 0.5886, 0.1983, 0.4989],
        [0.2493, 0.7782, 0.9517, 0.3815],
        [0.0937, 0.4765, 0.7531, 0.1426]])

In [23]:
random_tensor.shape

torch.Size([3, 4])

In [24]:
random_tensor.ndim

2

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

 ### Zeros and ones

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [29]:
# Use torch.range() and get deprecated message, use torch.arange()
torch.range(1, 11)

<ipython-input-29-de5287cb4a61>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [30]:
one_to_ten = torch.arange(1, 11)
#torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
random_range = torch.arange(start=89, end=200, step=25)
random_range

tensor([ 89, 114, 139, 164, 189])

In [32]:
#create zeros tensor of shape like provided tensor
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatype
**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

32 bit is single precision,
16 bit is half,
64 bit is double precision.

**Precision:** How much detail is stored in a number?

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_mix = float_32_tensor * float_16_tensor
float_mix

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensor (Tensor Attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not right device - to get device from a tensor, can use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4262, 0.4806, 0.0029, 0.4276],
        [0.7374, 0.0899, 0.9946, 0.0715],
        [0.6432, 0.2756, 0.5039, 0.9049]])

In [40]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4262, 0.4806, 0.0029, 0.4276],
        [0.7374, 0.0899, 0.9946, 0.0715],
        [0.6432, 0.2756, 0.5039, 0.9049]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [41]:
some_tensor.size() #size() is a function

torch.Size([3, 4])

In [42]:
some_tensor.shape #shape is an attribute

torch.Size([3, 4])

### Manipulating Tensors (Tensor operations)

Tensor operations includes:
1. Addition
2. Subtraction
3. Multiplication (element wise)
4. Division
5. Matrix Multiplication

In [43]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [48]:
torch.div(tensor, 3)

tensor([0.3333, 0.6667, 1.0000])

### Matrix Multiplication

Two main ways of performing multiplication in neutral networks and deeplearning
1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs ro satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimension**L
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [49]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[1.3984, 1.4023],
        [0.7882, 0.8538]])

In [50]:
# Element-wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [51]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.94 ms, sys: 0 ns, total: 1.94 ms
Wall time: 4.72 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.16 ms, sys: 30 µs, total: 1.19 ms
Wall time: 3.37 ms


tensor(14)

### One of the most common errors in deep learning is shape errors

In [54]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# tensor_A @ tensor_B = torch.mm(tensor_A, tensor_B) = tensor.matmul(tensor_A, tensor_B)
# tensor_A @ tensor_B
# throws an error as shape are different, inner dimensions are not same
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

##To fix the shape issues, we can manipulate the shape of one of our rensor using **transpose**

##A **transpose** switches the axes or dimension of a given tensor.

In [55]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [56]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [57]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as before), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as before), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [58]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [59]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [60]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [61]:

# Note: torch.mean() function requires a tensor of float 32 datatype to work (tensor not right datatype)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [62]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [63]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [64]:
# Find the position in tensor that has the minimum value with the argmin() -> returns the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [65]:
x[0]

tensor(1)

In [66]:
# Find the position in tensor that has the maximum value with the argmin() -> returns the index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but keep the smae memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Remove all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [68]:
# Create a tensor
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [69]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [70]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [71]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [72]:
# Stack tensors on top of each other
x_stacked_dim_0 = torch.stack([x, x, x, x], dim = 0)
x_stacked_dim_1 = torch.stack([x, x, x, x], dim = 1)
x_stacked_dim_0, x_stacked_dim_1


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]))

In [73]:
# Stack tensors on side of each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [74]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous Tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

# Remove extra dimensios from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous Tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous Shape: torch.Size([1, 9])

New Tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New Shape: torch.Size([9])


In [75]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimensions
print(f"Previous Tensor: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
#x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous Tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New Shape: torch.Size([1, 9])


In [76]:
# torch.permute - rearrange the dimension of a target tensor in a specified order
# Returns a view of the original tensor input with its dimensions permuted.
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]


# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts the axis 2->0, 0->1, 1->2


print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [77]:
x_original[0, 0, 0] = 786

In [78]:
x_permuted[0, 0, 0] # x_permuted shares same view as x_original

tensor(786.)

## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [79]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [82]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [83]:
# You can use ":" to select "all" of targer dimension
x[:, 0]

tensor([[1, 2, 3]])

In [84]:
# Get all values of 0th and 1st dimension and only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [85]:
# Get all values of 0th dimension but only the 1 index of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [86]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [87]:
# Index on x to return 9
print(x[0][2][2])
print(x[:, 2, 2]) # ':' selects all elements including dimension

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([9])
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data is NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [88]:
# NumPy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of floeat64 unless specified otherwise
# the default data type for tensor is float32
# tensor = torch.from_numpy(array).type(torch.float32) # changing datatype to float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
array.dtype

dtype('float64')

In [90]:
tensor.dtype

torch.float64

In [91]:
torch.arange(1.0, 10.0).dtype #default datatype float32, int32

torch.float32

In [92]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor
# from_numpy doesnt change the value of tensor, because they dont share the memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [93]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
numpy_tensor.dtype
# default dtype of numpy is float64, int64
# default dtype of tensor is float32, int32
# Here numpy_tensor reflecting the default dtype of tensor because it was created from tensor

dtype('float32')

In [95]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor
# value didnt change, because they dont share the memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
* `start with random number -> tensor operation -> update random number to try and make them better representation of the data -> again -> again -> again..,`

* To reduce the randomness is neural networks and PyTorch comes the concept of **random seed**.
Essentially what the random seed does is "flavour" the randomness.

In [96]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0848, 0.3283, 0.7109, 0.3749],
        [0.0092, 0.6502, 0.8539, 0.0190],
        [0.1421, 0.9475, 0.3545, 0.3336]])
tensor([[0.6642, 0.3746, 0.0887, 0.7833],
        [0.3769, 0.4757, 0.5895, 0.3643],
        [0.4806, 0.4491, 0.0787, 0.7554]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
# Let's make some random but reproducable tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # It only works on one block of code, so we have to call it again
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on number, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything excellent.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lot of options..., see this post: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch documentation: https://pytorch.org/get-started/locally/



In [98]:
!nvidia-smi

Mon Dec 25 00:19:57 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [99]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since its capable of running compute on the GPU or CPU, its best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices
E.g. run on GPU if available, else default to CPU

In [100]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [101]:
# Count number of devices
torch.cuda.device_count()

1

# 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [102]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [103]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [105]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy() # will result an error

In [113]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [107]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')